#!/usr/bin/perl

require "parser.pl";

&parse;

$out[0][0] = "Pos";
$out[1][0] = "Qty";
$out[2][0] = "P/N";
$out[3][0] = "Description";
$out[4][0] = "Value";
$out[5][0] = "";

for (sort keys %order) {
    push(@{ $out[0] }, ++$n);
    push(@{ $out[1] }, $order{$_}[0]);
    @f = split(/\s+/, $_);
    push(@{ $out[2] }, $f[1]);
    push(@{ $out[3] }, $dsc{$_});
    push(@{ $out[4] }, $order{$_}[1]);
    push(@{ $out[5] }, sprintf("%.2f", $order{$_}[2]));
}

for (@out) {
    push(@max, 0);
    for (@{ $_ }) {
	$max[$#max] = length $_ if length $_ > $max[$#max];
    }
}

for ($i = 0; $i < $#{ $out[0] }; $i++) {
    for ($j = 0; $j != 6; $j++) {
	my $s = $out[$j][$i];;
	print $s if $j == 2 || $j == 3 || $j == 4;
	print " " x ($max[$j]-length $s);
	print $s if $j == 0 || $j == 1 || $j == 5;
	print "  " unless $j == 5;
    }
    print "\n";
}
