#!/bin/sh


fail()
{
    echo FAILED "($SCRIPT)" 1>&2
    cat _out 1>&2
    exit 1
}


setup()
{
    /bin/echo -n "$1: " 1>&2
    shift
    ../envedit -o _env "$@" -P ../envcpp.pl -f - || fail
}


edit()
{
    ../envedit -i _env "$@" -P ../envcpp.pl -f - >_out 2>&1 || fail
}


edit_raw()
{
    ../envedit -i _env "$@" -n -f - >_out 2>&1 || fail
}


edit_fail()
{
    ../envedit -i _env "$@" -P ../envcpp.pl f - >_out 2>&1 && fail
}


edit_raw_fail()
{
    ../envedit -i _env "$@" -n -f - >_out 2>&1 && fail
}


expect()
{
    if ! diff -u - _out >_tmp; then
	echo FAILED "($SCRIPT)" 1>&2
	cat _tmp
	exit
    fi
    rm -f _env _out _tmp
    echo PASSED 1>&2
    passed=`expr ${passed:-0} + 1`
}
