#!/bin/sh
#valgrind --leak-check=full --show-reachable=yes --suppressions=leak.supp \
#  ./fped "$@"

#
# Seems that we can't suppress warnings from gtk_init, so we use FPED_NO_GUI
# to avoid bringing up Gtk+ at all.
#
FPED_NO_GUI=y valgrind --leak-check=full --show-reachable=yes \
  ./fped "$@"

#valgrind --leak-check=full --show-reachable=no \
#  ./fped "$@"
