#!/bin/sh
# Make a Library of Everything

COMPS="aat1275irn k4m51323pe lis302dl pcf50633-04-n3 s3c2442 wm8753lgefl"
COMPS="$COMPS ms2v-t1s si1040x tas4025a"
COMPS="$COMPS exc24cb102u dtc123 fa2012 rt9013_b rt9702 rt9711_bd_5 varistor"
COMPS="$COMPS 74x1g00_5 74x1g125 74x2g126 vibrator mini_usb_b smsn16"
COMPS="$COMPS sw_push_4 emh4 ht210 r3113d b7840 atr0610"
LIB=gta02-core.lib

for n in $COMPS; do
    if [ ! -r $n.lib ]; then
	echo $n.lib: cannot read 1>&2
	exit 1
    fi
done

for n in $COMPS; do
    cat $n.lib
done |
sed '1p;/^EESchema-LIBRARY/d;$p;/^#End/d' >$LIB
