#!/bin/sh

B=${1:-gta02-core}

OUT=$B-all
SHEETS="$B $B-CPU $B-CPU-POWER $B-PMU $B-MEMORY"
SHEETS="$SHEETS $B-AUDIO $B-USB $B-IO $B-LCM $B-SD-SIM"
SHEETS="$SHEETS $B-GPS $B-BT $B-WLAN"

psmerge `for n in $SHEETS; do echo $n.ps; done` |
  sed '1a%%Orientation: Landscape' >$OUT.ps
