#!/bin/sh

B=${1:-gta02-core}

OUT=$B-all
SHEETS="$B $B-CPU $B-PMU $B-MEMORY $B-AUDIO $B-IO $B-LCM $B-GPS"

psmerge `for n in $SHEETS; do echo $n.ps; done` |
  sed '1a%%Orientation: Landscape' >$OUT.ps
