#!/bin/bash

ps=true
pdf=false
shrink=false
cmd=shift_only


shift_only()
{
    # With the default settings, the right edge of the schematics gets cut off
    # on the screen and in printouts.
    # With -25, we get perfect on-screen display and almost no clipping on A4
    # printouts either.
    # This can be overridden locally by setting the environment variable
    # KICAD_PS_XSHIFT.

    pstops "0(0,${KICAD_PS_XSHIFT:--25})" "$@"
}


resize_and_shift()
{
    psresize -Pa3 -pa4 "$@" | shift_only
}


while [ "${1#-}" != "$1" ]; do
    case "$1" in
    --pdf)
	ps=false
	pdf=true;;
    --shrink)
	cmd=resize_and_shift
	shrink=true;;
    esac
    shift
done

B=${1:-gta02-core}

OUT=$B-all
SHEETS="$B $B-CPU $B-CPU-POWER $B-PMU $B-MEMORY"
SHEETS="$SHEETS $B-AUDIO $B-USB $B-IO $B-LCM $B-SD-SIM"
SHEETS="$SHEETS $B-GPS $B-BT $B-WLAN"

if $ps; then
    {
	sed 1q $B.ps
	sed '/^%%Orientation: /q;d' $B.ps
	$shrink || sed '/^%%DocumentMedia: /q;d' $B.ps
	eval psmerge `for n in $SHEETS; do [ -f $n.ps ] && \
	  echo "<($cmd $n.ps)"; done` | sed 1d
    } >$OUT.ps
fi

if $pdf; then
    eval gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$OUT.pdf -f \
      `for n in $SHEETS; do [ -f $n.ps ] && echo "<($cmd $n.ps)"; done`
fi
