#
# Specify which versions of OpenMoko packages to build
#

#
# Base
#

SRCDATE_gsm = "now"
SRCDATE_openmoko-session = "now"
SRCDATE_openmoko-common = "now"
SRCDATE_openmoko-theme-standard = "now"
SRCDATE_openmoko-libs = "now"

#
# Examples
#
SRCDATE_openmoko-stylus-demo = "now"
SRCDATE_openmoko-stylus-demo-simple = "now"
SRCDATE_openmoko-finger-demo = "now"

#
# Applications
#
SRCDATE_openmoko-chordmaster = "now"
SRCDATE_openmoko-dialer = "now"
SRCDATE_openmoko-footer = "now"
SRCDATE_openmoko-phone = "now"
SRCDATE_openmoko-mainmenu = "now"
SRCDATE_openmoko-taskmanager = "now"
