#!/bin/sh
#
# mknor - Make a GTA02 NOR binary (containing u-boot and a new environment)
#
# Copyright (C) 2008, 2009 by OpenMoko, Inc.
# Written by Werner Almesberger <werner@openmoko.org>
# All Rights Reserved
#

#
# Write to NOR with the following commands:
#
# - on the host, connected via a debugv3 board:
#   norwp rw
#
# - on the GTA02:
#   flash_unlock /dev/mtd0
#   flash_eraseall /dev/mtd0
#   cat nor.bin >/dev/mtd0
#
# To save time, the NOR can also be erased with
# flash_erase /dev/mtd0 0 13
# (or similar, depending on the image size)
#
# Or just use the "flashnor" script:
#
# norwp rw
# ifconfig usb0 192.168.0.200 up
# scp tmp/nor.bin flashnor 192.168.0.202:
# ssh 192.168.0.202 ./flashnor nor.bin
#

#
# NOR map:
#
# Physical address in MCU address space
# |    Offset in NOR
# |    |        Description
# |    |        |
# 0x18 00 0000	beginning of NOR, u-boot (256kB)
# 0x18 04 0000	splash image
# 0x18 05 0000	preboot command
# 0x18 05 0100	preboot script
# 0x18 05 1000	environment
# 0x18 1F FFFF	end of NOR (2MB)
#


usage()
{
cat <<EOF 1<&2
usage: $0 [-o outfile] [-s splash_image] [-D define ...] u-boot

  -o outfile       write NOR image to specified file. Default: nor.bin
  -s splash_image  use the specified splash image. Default: tmp/System_boot.png
  -D define        pass definition to envedit
EOF
    exit 1
}


out=nor.bin
splash=tmp/System_boot.png
defines=

while [ ! -z "$*" ]; do
    case "$1" in
        -o)	shift
		[ ! -z "$1" ] || usage
		out="$1";;
        -s)	shift
		[ ! -z "$1" ] || usage
		splash="$1";;
        -D)	shift
		[ ! -z "$1" ] || usage
		defines="$defines -D $1";;
        -*)	usage;;
	*)	break;;
    esac
    shift
done

[ ! -z "$1" -a -z "$2" ] || usage
uboot="$1"

./scriptify.pl <<EOF >_script
neo backlight off
neo backlight on
unzip 0x18040000 0x885dc00 0x38400
dynpart
echo READY.
EOF

pngtopnm "$splash" |
  pamcut 0 145 480 240 |
  ../splash/splashimg.pl -pnm - |
  gzip -9 >_splash

./envedit.pl -D GTA02 -D NOR_ENV $defines -f environment.in -o _env

./blink.pl \
  "$uboot"@0 \
  _splash@0x40000 \
  '"autoscr 0x18050100"'@0x50000 \
  _script@0x050100 \
  _env@0x51000 \
  0x18050000@=0x40 \
  0x18051004@0x44 \
  >$out || { rm -rf $out; exit 1; }

rm -f _splash _script _env
