#!/bin/sh
#
# mknor - Make a GTA02 NOR binary (containing u-boot and a new environment)
#
# Copyright (C) 2008 by OpenMoko, Inc.
# Written by Werner Almesberger <werner@openmoko.org>
# All Rights Reserved
#

#
# Write to NOR with the following commands:
#
# flash_unlock /dev/mtd0
# flash_eraseall /dev/mtd0
# cat nor.bin >/dev/mtd0
#
# To save time, the NOR can also be erased with
# flash_erase /dev/mtd0 0 13
# (or similar, depending on the image size)
#
# Or just use the "flashnor" script:
#
# norwp rw
# ifconfig usb0 192.168.0.200 up
# scp tmp/nor.bin flashnor 192.168.0.202:
# ssh 192.168.0.202 ./flashnor nor.bin
#

#
# NOR map:
#
# Physical address in MCU address space
# |    Offset in NOR
# |    |        Description
# |    |        |
# 0x18 00 0000	beginning of NOR, u-boot (256kB)
# 0x18 04 0000	splash image
# 0x18 05 0000	preboot command
# 0x18 05 0100	preboot script
# 0x18 05 1000	environment
# 0x18 1F FFFF	end of NOR (2MB)
#


usage()
{
    echo "usage: $0 [-o outfile ] u-boot" 1>&2
    exit 1
}


out=nor.bin
if [ "$1" = -o ]; then
    [ ! -z "$2" ] || usage
    out="$2"
    shift 2
fi
[ ! -z "$1" -a -z "$2" ] || usage
uboot="$1"

./scriptify.pl <<EOF >_script
neo backlight off
neo backlight on
unzip 0x18040000 0x885dc00 0x38400
dynpart
echo READY.
EOF

pngtopnm tmp/System_boot.png |
  pamcut 0 145 480 240 |
  ../splash/splashimg.pl -pnm - |
  gzip -9 >_splash

./envedit.pl -D GTA02 -D NOR_ENV -f environment.in -o _env

./blink.pl \
  "$1"@0 \
  _splash@0x40000 \
  '"autoscr 0x18050100"'@0x50000 \
  _script@0x050100 \
  _env@0x51000 \
  0x18050000@=0x40 \
  0x18051004@0x44 \
  >$out || { rm -rf $out; exit 1; }

rm -f _splash _script _env
